library(foreach)
library(doMC)
registerDoMC()
library(multtest)
library(WGCNA)
library("org.Mm.eg.db")
library(biomaRt)
library(GOstats)
library("org.Mm.eg.db")
library("edgeR")
library(vegan)
library(sgof)

library(lawstat)
library(openxlsx)

#source("http://bioconductor.org/biocLite.R")
# biocLite("org.Mm.eg.db")
#biocLite("GOstats")

getDoParWorkers()
options(cores=27)
getDoParWorkers()

#enableWGCNAThreads(nThreads = 27)


setwd("/lawrencedata/ongoing_analyses/RNA160225TP/all_fastq/Alignment_mm10/Read_counts_and_normalization/GeneNetworkAnalysis")

source("/home/dan/workDir/functionDefinitions.R")

Table1_CoexprModulesDEDV=read.csv("resultsCoexpr/SummaryResultsDEDV.csv")
Table2_CoexprModulesGO=read.csv("resultsCoexpr/affectedGenesCoexprGO.csv")
Table3_CoexprCellTypeEnrichment=read.csv("resultsCoexpr/cellTypeEnrich.csv")
Table4_CoexprAffectedGenesDEDV=read.csv("resultsCoexpr/affectedGenesDEDV.csv")
Table5_CoexprAffectedGenesGO=read.csv("resultsCoexpr/affectedGenesDEDV.csv")

Table6_CoSplicExModulesDS=read.csv("resultsCoexpr/SummaryResultsCoexpr.txt")
Table7_CoSplicExModulesGO=read.csv("resultsCoSplicEx/modulesCoSplicExGO.csv")
Table8_CoSplicExCellTypeEnrichment=read.csv("resultsCoSplicEx/cellTypeEnrich.csv")
Table9_CoSplicExAffectedGenesDS=read.csv("resultsCoSplicEx/affectedGenesDS.csv")
Table10_CoSplicExAffectedGenesGO=read.csv("resultsCoSplicEx/affectedGenesCoSplicExGO.csv")
Table11_CoSplicExAffectedExons=read.csv("resultsCoSplicEx/summaryResultsExon.csv")

wb <- createWorkbook()
addWorksheet(wb = wb, sheetName = "Table1_CoexprModulesDEDV")
addWorksheet(wb = wb, sheetName = "Table2_CoexprModulesGO")
addWorksheet(wb = wb, sheetName = "Table3_CoexprCellTypeEnrichment")
addWorksheet(wb = wb, sheetName = "Table4_CoexprAffectedGenesDEDV")
addWorksheet(wb = wb, sheetName = "Table5_CoexprAffectedGenesGO")
writeDataTable(wb = wb, sheet = "Table1_CoexprModulesDEDV", x = Table1_CoexprModulesDEDV )
writeDataTable(wb = wb, sheet = "Table2_CoexprModulesGO", x = Table2_CoexprModulesGO )
writeDataTable(wb = wb, sheet = "Table3_CoexprCellTypeEnrichment", x = Table3_CoexprCellTypeEnrichment )
writeDataTable(wb = wb, sheet = "Table4_CoexprAffectedGenesDEDV", x = Table4_CoexprAffectedGenesDEDV )
writeDataTable(wb = wb, sheet = "Table5_CoexprAffectedGenesGO", x = Table5_CoexprAffectedGenesGO )
saveWorkbook(wb, "SupplementaryTables.xlsx", overwrite = TRUE)

write.xlsx(Table1_CoexprModulesDEDV, file="SupplementaryTables.xlsx", sheetName="Table1_CoexprModulesDEDV")
write.xlsx(Table2_CoexprModulesGO, file="SupplementaryTables.xlsx", sheetName="Table2_CoexprModulesGO", append=TRUE)
write.xlsx(Table3_CoexprCellTypeEnrichment, file="SupplementaryTables.xlsx", sheetName="Table3_CoexprCellTypeEnrichment", append=TRUE)
write.xlsx(Table4_CoexprAffectedGenesDEDV, file="SupplementaryTables.xlsx", sheetName="Table4_CoexprAffectedGenesDEDV", append=TRUE)
write.xlsx(Table5_CoexprAffectedGenesGO, file="SupplementaryTables.xlsx", sheetName="Table5_CoexprAffectedGenesGO", append=TRUE)

write.xlsx(Table6_CoSplicExModulesDS, file="SupplementaryTables.xlsx", sheetName="Table6_CoSplicExModulesDS")
write.xlsx(Table7_CoSplicExModulesGO, file="SupplementaryTables.xlsx", sheetName="Table7_CoSplicExModulesGO", append=TRUE)
write.xlsx(Table8_CoSplicExCellTypeEnrichment, file="SupplementaryTables.xlsx", sheetName="Table8_CoSplicExCellTypeEnrichment", append=TRUE)
write.xlsx(Table9_CoSplicExAffectedGenesDS, file="SupplementaryTables.xlsx", sheetName="Table9_CoSplicExAffectedGenesDS", append=TRUE)
write.xlsx(Table10_CoSplicExAffectedGenesGO, file="SupplementaryTables.xlsx", sheetName="Table10_CoSplicExAffectedGenesGO", append=TRUE)
write.xlsx(Table11_CoSplicExAffectedExons, file="SupplementaryTables.xlsx", sheetName="Table11_CoSplicExAffectedExons", append=TRUE)
